spring:
  cloud:
    consul:
      host: 192.168.2.215
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}
  application:
    name: discovery-consul