spring:
  application:
    name: discovery-eureka-peer1
server:
  port: 9761
eureka:
  instance:
    metadataMap.zone: zone1                       #将注册分别在不同区域运行，增加该区域的高可用性
    hostname: peer1                               # 指定当profile=peer1时，主机名
  client:
    preferSameZoneEureka: true
    #    healthcheck.enabled: true 疑似已经取消该参数，每个应用基本上都是要使用到的，因此设置这个参数有些多此一举的感觉
    serviceUrl.defaultZone: http://peer2:9762/eureka/     # 将自己注册到peer2这个Eureka上面去
